export const PLANS = {
  free: {
    name: 'Gratis',
    badge: 'FREE',
    price: 0,
    priceLabel: 'Selamanya gratis',
    color: '#78716c',
    maxMembers: 15,
    maxFamilyLogins: 5,
    features: {
      kinship: false,
      maps: false,
      exportExcel: false,
      importExcel: false,
      photoUpload: false,
      unlimitedTree: false,
    },
    featureList: [
      '✓ Hingga 15 anggota keluarga',
      '✓ Pohon silsilah visual',
      '✓ Tabel data keluarga',
      '✓ 5 slot login anggota',
      '✗ Kalkulator nasab',
      '✗ Klik ke Google Maps',
      '✗ Export Excel',
      '✗ Upload foto',
    ],
  },
  starter: {
    name: 'Starter',
    badge: 'STARTER',
    price: 29000,
    priceLabel: 'per bulan',
    color: '#0284c7',
    maxMembers: 50,
    maxFamilyLogins: 20,
    features: {
      kinship: true,
      maps: true,
      exportExcel: true,
      importExcel: false,
      photoUpload: true,
      unlimitedTree: false,
    },
    featureList: [
      '✓ Hingga 50 anggota keluarga',
      '✓ Pohon silsilah visual',
      '✓ Tabel data keluarga',
      '✓ 20 slot login anggota',
      '✓ Kalkulator nasab',
      '✓ Klik ke Google Maps',
      '✓ Export Excel',
      '✓ Upload foto anggota',
    ],
  },
  family: {
    name: 'Family',
    badge: 'POPULAR',
    price: 79000,
    priceLabel: 'per bulan',
    color: '#d97706',
    maxMembers: 100,
    maxFamilyLogins: 50,
    features: {
      kinship: true,
      maps: true,
      exportExcel: true,
      importExcel: true,
      photoUpload: true,
      unlimitedTree: false,
    },
    featureList: [
      '✓ Hingga 100 anggota keluarga',
      '✓ Pohon silsilah visual',
      '✓ Tabel data keluarga',
      '✓ 50 slot login anggota',
      '✓ Kalkulator nasab',
      '✓ Klik ke Google Maps',
      '✓ Export & Import Excel',
      '✓ Upload foto anggota',
    ],
  },
  unlimited: {
    name: 'Unlimited',
    badge: 'ULTIMATE',
    price: 149000,
    priceLabel: 'per bulan',
    color: '#7c3aed',
    maxMembers: Infinity,
    maxFamilyLogins: Infinity,
    features: {
      kinship: true,
      maps: true,
      exportExcel: true,
      importExcel: true,
      photoUpload: true,
      unlimitedTree: true,
    },
    featureList: [
      '✓ Anggota tak terbatas',
      '✓ Pohon silsilah visual',
      '✓ Tabel data keluarga',
      '✓ Login anggota tak terbatas',
      '✓ Kalkulator nasab',
      '✓ Klik ke Google Maps',
      '✓ Export & Import Excel',
      '✓ Upload foto anggota',
    ],
  },
};

export const getPlanConfig = (planName) => PLANS[planName] || PLANS.free;
